variables:
- group: Semgrep_Mayowa

jobs:
- job: Semgrep_Scan
  steps:
    - script: |
        python -m pip install --upgrade pip
        pip install semgrep
        echo $(System.PullRequest.PullRequestId)
        if [ $(Build.SourceBranchName) = "master" ]; then
            echo "Semgrep full scan"
            semgrep login
            semgrep ci
        elif [ $(System.PullRequest.PullRequestId) -ge 0 ]; then
            echo "Semgrep diff scan"
            export SEMGREP_PR_ID=$(System.PullRequest.PullRequestId)
            export SEMGREP_BASELINE_REF='origin/master'
            git fetch origin master:origin/master
            semgrep login
            semgrep ci
        fi
      env:
        SEMGREP_APP_TOKEN: $(SEMGREP_APP_TOKEN)
        SEMGREP_BASELINE_REF: 'origin/master'
        SEMGREP_PR_ID: $(System.PullRequest.PullRequestNumber)    
        