variables:
- group: Semgrep_Mayowa

jobs:
- job: Semgrep_Scan
  steps:
    - script: |
        python -m pip install --upgrade pip
        pip install semgrep
        if [ $(Build.SourceBranchName) = "master" ]; then
            echo "Semgrep full scan"
            semgrep login
            semgrep ci
        elif [ $(Build.SourceBranchName) != "master" ]; then
            echo "Semgrep diff scan"
            echo "Pull Request Scan from branch: $(Build.SourceBranchName)"
            git fetch origin master:origin/master
            semgrep login
            semgrep ci
        fi
      env:
        SEMGREP_APP_TOKEN: $(SEMGREP_APP_TOKEN)       